name: protocol_registry
description: Register/query/remove URI Schemes without hassle. Available for Windows and Linux.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  http: ^0.13.3
  path: ^1.8.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter: